# branches to build
branches:
  # whitelist
  only:
    - master

# build version format
version: '{build}'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 12

# Get the stable version of node
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

build: off

test_script:
  - cmd: npm test
